name: Build and Upload ZIP on Release Published

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Python セットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 依存をインストール
        run: pip install -r requirements.txt

      - name: PyInstallerでビルド
        run: pyinstaller hello.spec

      - name: ZIPファイルを作成（exe + README）
        run: |
          powershell Compress-Archive -Path dist/hello.exe, README.md -DestinationPath dist/hello.zip

      - name: リリースにZIPをアップロード
        uses: softprops/action-gh-release@v1
        with:
          files: dist/hello.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
