name: Github Action training
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run Script in trial
        # shell: pwsh
        run: |
          echo "Hello ! This is trial workflow"

