name: Github Action training
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Explore-Github-Actions:
    runs-on: windows-latest
    steps:
      - name: run PSScript in trial
        shell: pwsh
        run: |
          echo "Hello ! This is trial workflow"

