name: Main workflow

on:
  push:

jobs:
  Main-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/github-actions-demo.yml
      - name: run PSScript in main
        shell: pwsh
        run: |
          echo "Hello ! This is main workflow"
